# Generated by Django 5.0.6 on 2026-09-30 10:12

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("billing", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Purchase",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("purchase_number", models.CharField(max_length=50, unique=True)),
                ("supplier_name", models.CharField(default="Vendor", max_length=200)),
                (
                    "total_amount",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
                ),
                ("payment_status", models.CharField(default="Paid", max_length=20)),
                ("notes", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.AlterModelOptions(
            name="product",
            options={"ordering": ["name_tamil", "name"]},
        ),
        migrations.AddField(
            model_name="invoice",
            name="balance_amount",
            field=models.DecimalField(
                decimal_places=2,
                default=0.0,
                help_text="Remaining balance due",
                max_digits=12,
            ),
        ),
        migrations.AddField(
            model_name="invoice",
            name="paid_amount",
            field=models.DecimalField(
                decimal_places=2,
                default=0.0,
                help_text="Amount customer paid",
                max_digits=12,
            ),
        ),
        migrations.AddField(
            model_name="invoiceitem",
            name="unit",
            field=models.CharField(default="KG", max_length=20),
        ),
        migrations.AddField(
            model_name="product",
            name="name_tamil",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Tamil Name (e.g. அரிசி, சர்க்கரை)",
                max_length=200,
            ),
        ),
        migrations.AlterField(
            model_name="invoice",
            name="payment_method",
            field=models.CharField(
                choices=[
                    ("Cash", "Cash"),
                    ("Online", "Online Payment (UPI/Card)"),
                    ("Bank Transfer", "Bank Transfer"),
                    ("Credit", "Credit / Due"),
                ],
                default="Cash",
                max_length=30,
            ),
        ),
        migrations.AlterField(
            model_name="invoice",
            name="payment_status",
            field=models.CharField(
                choices=[
                    ("Paid", "Paid"),
                    ("Pending", "Pending / Due"),
                    ("Partial", "Partial"),
                ],
                default="Paid",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="cost_price",
            field=models.DecimalField(
                decimal_places=2,
                default=0.0,
                help_text="Purchase / Buy price",
                max_digits=12,
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="name",
            field=models.CharField(
                blank=True,
                default="",
                help_text="English Name (Optional)",
                max_length=200,
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="unit",
            field=models.CharField(
                choices=[
                    ("KG", "Kilogram (KG)"),
                    ("Pack", "Pack / Bag (Pack)"),
                    ("Box", "Box"),
                    ("Pcs", "Pieces (Pcs)"),
                    ("Ltr", "Liter (Ltr)"),
                ],
                default="KG",
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="ActiveUserSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("session_key", models.CharField(max_length=40, unique=True)),
                (
                    "device_info",
                    models.CharField(default="Desktop/Mobile Browser", max_length=255),
                ),
                ("ip_address", models.CharField(default="127.0.0.1", max_length=50)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("last_activity", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="active_sessions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-last_activity"],
            },
        ),
        migrations.CreateModel(
            name="PaymentRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "payment_method",
                    models.CharField(
                        choices=[
                            ("Cash", "Cash"),
                            ("Online", "Online Payment (UPI/Card)"),
                            ("Bank Transfer", "Bank Transfer"),
                            ("Credit", "Credit / Due"),
                        ],
                        default="Cash",
                        max_length=30,
                    ),
                ),
                ("notes", models.CharField(blank=True, default="", max_length=200)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "invoice",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payments",
                        to="billing.invoice",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
