# Generated by Django 5.0.6 on 2026-09-30 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("billing", "0003_activitylog_userprofile"),
    ]

    operations = [
        migrations.CreateModel(
            name="CompanySettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "company_name",
                    models.CharField(default="SmartBilling Store", max_length=200),
                ),
                (
                    "address",
                    models.TextField(
                        blank=True, default="Main Market Road, Commercial Complex"
                    ),
                ),
                (
                    "phone",
                    models.CharField(
                        blank=True, default="+91 98765 43210", max_length=50
                    ),
                ),
                (
                    "email",
                    models.CharField(
                        blank=True, default="contact@smartbilling.local", max_length=100
                    ),
                ),
                (
                    "gst_number",
                    models.CharField(
                        blank=True, default="27AABCS1429B1Z", max_length=50
                    ),
                ),
                (
                    "logo_image",
                    models.ImageField(
                        blank=True, null=True, upload_to="company_logos/"
                    ),
                ),
                (
                    "watermark_image",
                    models.ImageField(
                        blank=True, null=True, upload_to="company_watermarks/"
                    ),
                ),
                ("logo_base64", models.TextField(blank=True, default="")),
                ("watermark_base64", models.TextField(blank=True, default="")),
                (
                    "auto_delete_days",
                    models.IntegerField(
                        default=45,
                        help_text="Auto-delete customer data older than X days",
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Company Profile & Branding",
                "verbose_name_plural": "Company Profile & Branding",
            },
        ),
        migrations.AlterField(
            model_name="activitylog",
            name="action_type",
            field=models.CharField(
                choices=[
                    ("LOGIN", "User Login"),
                    ("LOGOUT", "User Logout"),
                    ("INVOICE_CREATE", "Invoice Created"),
                    ("PAYMENT_UPDATE", "Payment Updated"),
                    ("DISCOUNT_APPLIED", "Offer / Discount Applied"),
                    ("PRODUCT_ADD", "Product Added"),
                    ("PRODUCT_EDIT", "Product Edited"),
                    ("PRODUCT_DELETE", "Product Removed"),
                    ("CUSTOMER_ADD", "Customer Added"),
                    ("CUSTOMER_EDIT", "Customer Altered"),
                    ("USER_CREATE", "User Created"),
                    ("USER_EDIT", "User Account Edited"),
                    ("PASSWORD_CHANGE", "Password Reset"),
                    ("INVOICE_EDIT", "Invoice Altered / Edited"),
                    ("DATA_CLEANUP", "45-Day Data Cleanup"),
                    ("COMPANY_UPDATE", "Company Profile & Branding Updated"),
                ],
                db_index=True,
                max_length=50,
            ),
        ),
    ]
