# Generated by Django 5.0.6 on 2026-09-30 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("billing", "0004_companysettings_alter_activitylog_action_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="avatar_base64",
            field=models.TextField(
                blank=True, default="", help_text="Base64 encoded client profile image"
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="avatar_image",
            field=models.ImageField(blank=True, null=True, upload_to="client_avatars/"),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="shop_name",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Client Business / Shop Name",
                max_length=150,
            ),
        ),
        migrations.AlterField(
            model_name="activitylog",
            name="action_type",
            field=models.CharField(
                choices=[
                    ("LOGIN", "User Login"),
                    ("LOGOUT", "User Logout"),
                    ("INVOICE_CREATE", "Invoice Created"),
                    ("PAYMENT_UPDATE", "Payment Updated"),
                    ("DISCOUNT_APPLIED", "Offer / Discount Applied"),
                    ("PRODUCT_ADD", "Product Added"),
                    ("PRODUCT_EDIT", "Product Edited"),
                    ("PRODUCT_DELETE", "Product Removed"),
                    ("CUSTOMER_ADD", "Customer Added"),
                    ("CUSTOMER_EDIT", "Customer Altered"),
                    ("USER_CREATE", "User Created"),
                    ("USER_EDIT", "User Account Edited"),
                    ("USER_DELETE", "User Account Deleted"),
                    ("SESSION_REVOKE", "Device Session Disconnected"),
                    ("PASSWORD_CHANGE", "Password Reset"),
                    ("INVOICE_EDIT", "Invoice Altered / Edited"),
                    ("DATA_CLEANUP", "45-Day Data Cleanup"),
                    ("COMPANY_UPDATE", "Company Profile & Branding Updated"),
                ],
                db_index=True,
                max_length=50,
            ),
        ),
    ]
