# Generated by Django 5.0.6 on 2026-10-03 07:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("billing", "0005_userprofile_avatar_base64_userprofile_avatar_image_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Branch",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Branch / Shop Name (e.g. Main Shop, Branch 1)",
                        max_length=150,
                    ),
                ),
                (
                    "branch_code",
                    models.CharField(
                        help_text="Branch Identifier Code (e.g. BR-01)",
                        max_length=50,
                        unique=True,
                    ),
                ),
                ("phone", models.CharField(blank=True, default="", max_length=20)),
                ("email", models.EmailField(blank=True, default="", max_length=254)),
                ("address", models.TextField(blank=True, default="")),
                (
                    "manager_name",
                    models.CharField(blank=True, default="", max_length=150),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("is_default", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.AddField(
            model_name="customer",
            name="notes",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="invoice",
            name="branch_name",
            field=models.CharField(
                blank=True, default="Main Shop Branch", max_length=150
            ),
        ),
        migrations.AlterField(
            model_name="activitylog",
            name="action_type",
            field=models.CharField(
                choices=[
                    ("LOGIN", "User Login"),
                    ("LOGOUT", "User Logout"),
                    ("INVOICE_CREATE", "Invoice Created"),
                    ("PAYMENT_UPDATE", "Payment Updated"),
                    ("DISCOUNT_APPLIED", "Offer / Discount Applied"),
                    ("PRODUCT_ADD", "Product Added"),
                    ("PRODUCT_EDIT", "Product Edited"),
                    ("PRODUCT_DELETE", "Product Removed"),
                    ("CUSTOMER_ADD", "Customer Added"),
                    ("CUSTOMER_EDIT", "Customer Altered"),
                    ("USER_CREATE", "User Created"),
                    ("USER_EDIT", "User Account Edited"),
                    ("USER_DELETE", "User Account Deleted"),
                    ("SESSION_REVOKE", "Device Session Disconnected"),
                    ("PASSWORD_CHANGE", "Password Reset"),
                    ("INVOICE_EDIT", "Invoice Altered / Edited"),
                    ("DATA_CLEANUP", "Data Cleanup"),
                    ("COMPANY_UPDATE", "Company Profile & Branding Updated"),
                    ("BRANCH_CREATE", "Shop Branch Created"),
                    ("BRANCH_EDIT", "Shop Branch Updated"),
                    ("BRANCH_DELETE", "Shop Branch Deleted"),
                    ("STOCK_ADD", "Stock Inward / Added"),
                    ("STOCK_UPDATE", "Stock Quantity Adjusted"),
                    ("CUSTOMER_DELETE", "Customer Record Deleted"),
                ],
                db_index=True,
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name="invoice",
            name="branch",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="invoices",
                to="billing.branch",
            ),
        ),
        migrations.CreateModel(
            name="StockLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "change_type",
                    models.CharField(
                        choices=[
                            ("BILLING_SALE", "Customer Purchase Sale"),
                            ("RESTOCK", "Stock Inward / Addition"),
                            ("MANUAL_ADJUSTMENT", "Manual Stock Quantity Adjustment"),
                            ("BILLING_RESTORE", "Bill Edit / Stock Restored"),
                        ],
                        default="RESTOCK",
                        max_length=30,
                    ),
                ),
                (
                    "quantity_change",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Positive for additions, negative for sales",
                        max_digits=10,
                    ),
                ),
                (
                    "previous_quantity",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
                ),
                (
                    "new_quantity",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
                ),
                ("notes", models.TextField(blank=True, default="")),
                ("created_by", models.CharField(default="Admin", max_length=150)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "invoice",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="stock_logs",
                        to="billing.invoice",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stock_logs",
                        to="billing.product",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
