# Generated by Django 5.0.6 on 2026-10-03 08:11

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("billing", "0006_branch_customer_notes_invoice_branch_name_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SoftwareUpdate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("version", models.CharField(default="v2.5.0", max_length=50)),
                (
                    "title",
                    models.CharField(
                        default="System Improvements & Updates", max_length=200
                    ),
                ),
                ("release_notes", models.TextField(blank=True, default="")),
                ("is_published", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "published_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddField(
            model_name="branch",
            name="client",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="branches",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="companysettings",
            name="account_number",
            field=models.CharField(
                blank=True,
                default="30294819283",
                help_text="Bank Account Number",
                max_length=60,
            ),
        ),
        migrations.AddField(
            model_name="companysettings",
            name="bank_name",
            field=models.CharField(
                blank=True,
                default="State Bank of India",
                help_text="Bank Name",
                max_length=150,
            ),
        ),
        migrations.AddField(
            model_name="companysettings",
            name="ifsc_code",
            field=models.CharField(
                blank=True,
                default="SBIN0001234",
                help_text="Bank IFSC Code",
                max_length=30,
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="account_number",
            field=models.CharField(
                blank=True, default="", help_text="Bank Account Number", max_length=60
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="bank_name",
            field=models.CharField(
                blank=True, default="", help_text="Bank Name", max_length=150
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="business_type",
            field=models.CharField(
                choices=[
                    ("grocery", "Grocery Shop"),
                    ("mobile_computer", "Mobile & Computer Shop"),
                ],
                default="grocery",
                help_text="Store Business Category",
                max_length=30,
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="device_limit",
            field=models.IntegerField(
                default=5, help_text="Maximum allowed active devices"
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="ifsc_code",
            field=models.CharField(
                blank=True, default="", help_text="Bank IFSC Code", max_length=30
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="shop_address",
            field=models.TextField(
                blank=True, default="", help_text="Client Business / Shop Address"
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="shop_logo_base64",
            field=models.TextField(
                blank=True, default="", help_text="Base64 encoded shop logo"
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="shop_logo_image",
            field=models.ImageField(blank=True, null=True, upload_to="client_logos/"),
        ),
        migrations.AlterField(
            model_name="activitylog",
            name="action_type",
            field=models.CharField(
                choices=[
                    ("LOGIN", "User Login"),
                    ("LOGOUT", "User Logout"),
                    ("INVOICE_CREATE", "Invoice Created"),
                    ("PAYMENT_UPDATE", "Payment Updated"),
                    ("DISCOUNT_APPLIED", "Offer / Discount Applied"),
                    ("PRODUCT_ADD", "Product Added"),
                    ("PRODUCT_EDIT", "Product Edited"),
                    ("PRODUCT_DELETE", "Product Removed"),
                    ("CUSTOMER_ADD", "Customer Added"),
                    ("CUSTOMER_EDIT", "Customer Altered"),
                    ("USER_CREATE", "User Created"),
                    ("USER_EDIT", "User Account Edited"),
                    ("USER_DELETE", "User Account Deleted"),
                    ("SESSION_REVOKE", "Device Session Disconnected"),
                    ("PASSWORD_CHANGE", "Password Reset"),
                    ("INVOICE_EDIT", "Invoice Altered / Edited"),
                    ("DATA_CLEANUP", "Data Cleanup"),
                    ("COMPANY_UPDATE", "Company Profile & Branding Updated"),
                    ("BRANCH_CREATE", "Shop Branch Created"),
                    ("BRANCH_EDIT", "Shop Branch Updated"),
                    ("BRANCH_DELETE", "Shop Branch Deleted"),
                    ("STOCK_ADD", "Stock Inward / Added"),
                    ("STOCK_UPDATE", "Stock Quantity Adjusted"),
                    ("CUSTOMER_DELETE", "Customer Record Deleted"),
                    ("UPDATE_PUBLISH", "Software Update Published"),
                    ("PROFILE_UPDATE", "Client Profile & Business Details Updated"),
                    ("REPORT_EXPORT", "Statement / Sales Report Exported"),
                ],
                db_index=True,
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="unit",
            field=models.CharField(
                choices=[
                    ("KG", "Kilogram (KG)"),
                    ("Gram", "Gram (g)"),
                    ("Pack", "Pack / Bag (Pack)"),
                    ("Box", "Box"),
                    ("Pcs", "Pieces (Pcs)"),
                    ("Ltr", "Liter (Ltr)"),
                    ("Set", "Set"),
                    ("Nos", "Numbers (Nos)"),
                    ("Unit", "Unit"),
                ],
                default="KG",
                max_length=20,
            ),
        ),
    ]
