# Generated by Django 5.0.6 on 2026-10-06 05:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("billing", "0008_customer_client_invoice_client_product_client_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="access_mode",
            field=models.CharField(
                choices=[
                    ("online_offline", "Online & Offline (Web + Desktop App)"),
                    ("offline_only", "Offline POS Only (Desktop EXE)"),
                    ("online_only", "Online Only (Web Portal)"),
                ],
                default="online_offline",
                help_text="Platform access permissions",
                max_length=30,
            ),
        ),
        migrations.AlterField(
            model_name="activitylog",
            name="action_type",
            field=models.CharField(
                choices=[
                    ("LOGIN", "User Login"),
                    ("LOGOUT", "User Logout"),
                    ("INVOICE_CREATE", "Invoice Created"),
                    ("PAYMENT_UPDATE", "Payment Updated"),
                    ("DISCOUNT_APPLIED", "Offer / Discount Applied"),
                    ("PRODUCT_ADD", "Product Added"),
                    ("PRODUCT_EDIT", "Product Edited"),
                    ("PRODUCT_DELETE", "Product Removed"),
                    ("CUSTOMER_ADD", "Customer Added"),
                    ("CUSTOMER_EDIT", "Customer Altered"),
                    ("USER_CREATE", "User Created"),
                    ("USER_EDIT", "User Account Edited"),
                    ("USER_DELETE", "User Account Deleted"),
                    ("SESSION_REVOKE", "Device Session Disconnected"),
                    ("PASSWORD_CHANGE", "Password Reset"),
                    ("INVOICE_EDIT", "Invoice Altered / Edited"),
                    ("DATA_CLEANUP", "Data Cleanup"),
                    ("COMPANY_UPDATE", "Company Profile & Branding Updated"),
                    ("BRANCH_CREATE", "Shop Branch Created"),
                    ("BRANCH_EDIT", "Shop Branch Updated"),
                    ("BRANCH_DELETE", "Shop Branch Deleted"),
                    ("STOCK_ADD", "Stock Inward / Added"),
                    ("STOCK_UPDATE", "Stock Quantity Adjusted"),
                    ("CUSTOMER_DELETE", "Customer Record Deleted"),
                    ("UPDATE_PUBLISH", "Software Update Published"),
                    ("PROFILE_UPDATE", "Client Profile & Business Details Updated"),
                    ("REPORT_EXPORT", "Statement / Sales Report Exported"),
                    ("DEVICE_REGISTER", "Device Registered / Activated"),
                    ("DEVICE_REVOKE", "Device Access Revoked"),
                    ("DEVICE_LIMIT_BLOCKED", "Device Quota Exceeded Blocked"),
                ],
                db_index=True,
                max_length=50,
            ),
        ),
        migrations.CreateModel(
            name="RegisteredDevice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "device_id",
                    models.CharField(
                        db_index=True,
                        help_text="Unique hardware/device fingerprint",
                        max_length=120,
                    ),
                ),
                (
                    "device_name",
                    models.CharField(default="POS Terminal", max_length=150),
                ),
                (
                    "device_type",
                    models.CharField(
                        choices=[
                            ("desktop_exe", "Windows Desktop POS (EXE)"),
                            ("web_browser", "Web Browser / Mobile"),
                        ],
                        default="desktop_exe",
                        max_length=50,
                    ),
                ),
                ("ip_address", models.CharField(default="127.0.0.1", max_length=50)),
                ("is_active", models.BooleanField(default=True)),
                ("last_login", models.DateTimeField(auto_now=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="registered_devices",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-last_login"],
                "unique_together": {("user", "device_id")},
            },
        ),
    ]
