# Generated by Django 5.0.6 on 2026-10-06 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("billing", "0009_userprofile_access_mode_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="gst_number",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Client Business GSTIN Number",
                max_length=50,
            ),
        ),
    ]
