# Generated by Django 5.0.6 on 2026-10-07 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("billing", "0011_alter_companysettings_gst_number_productcategory"),
    ]

    operations = [
        migrations.AddField(
            model_name="registereddevice",
            name="is_verified",
            field=models.BooleanField(
                default=True, help_text="True if admin verified or approved via OTP"
            ),
        ),
        migrations.AddField(
            model_name="registereddevice",
            name="otp_code",
            field=models.CharField(
                blank=True,
                default="",
                help_text="6-digit activation code sent to admin panel",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="registereddevice",
            name="otp_created_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="activitylog",
            name="action_type",
            field=models.CharField(
                choices=[
                    ("LOGIN", "User Login"),
                    ("LOGOUT", "User Logout"),
                    ("INVOICE_CREATE", "Invoice Created"),
                    ("PAYMENT_UPDATE", "Payment Updated"),
                    ("DISCOUNT_APPLIED", "Offer / Discount Applied"),
                    ("PRODUCT_ADD", "Product Added"),
                    ("PRODUCT_EDIT", "Product Edited"),
                    ("PRODUCT_DELETE", "Product Removed"),
                    ("CUSTOMER_ADD", "Customer Added"),
                    ("CUSTOMER_EDIT", "Customer Altered"),
                    ("USER_CREATE", "User Created"),
                    ("USER_EDIT", "User Account Edited"),
                    ("USER_DELETE", "User Account Deleted"),
                    ("SESSION_REVOKE", "Device Session Disconnected"),
                    ("PASSWORD_CHANGE", "Password Reset"),
                    ("INVOICE_EDIT", "Invoice Altered / Edited"),
                    ("DATA_CLEANUP", "Data Cleanup"),
                    ("COMPANY_UPDATE", "Company Profile & Branding Updated"),
                    ("BRANCH_CREATE", "Shop Branch Created"),
                    ("BRANCH_EDIT", "Shop Branch Updated"),
                    ("BRANCH_DELETE", "Shop Branch Deleted"),
                    ("STOCK_ADD", "Stock Inward / Added"),
                    ("STOCK_UPDATE", "Stock Quantity Adjusted"),
                    ("CUSTOMER_DELETE", "Customer Record Deleted"),
                    ("UPDATE_PUBLISH", "Software Update Published"),
                    ("PROFILE_UPDATE", "Client Profile & Business Details Updated"),
                    ("REPORT_EXPORT", "Statement / Sales Report Exported"),
                    ("DEVICE_REGISTER", "Device Registered / Activated"),
                    ("DEVICE_REVOKE", "Device Access Revoked"),
                    ("DEVICE_LIMIT_BLOCKED", "Device Quota Exceeded Blocked"),
                    ("DEVICE_OTP", "New Device Verification OTP"),
                    ("DEVICE_VERIFY", "Device OTP Verified & Approved"),
                ],
                db_index=True,
                max_length=50,
            ),
        ),
    ]
