# Generated by Django 5.0.6 on 2026-10-08 12:56

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("billing", "0013_invoice_customer_address_alter_product_sku_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="customer",
            name="deleted_at",
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name="customer",
            name="is_deleted",
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name="invoice",
            name="deleted_at",
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name="invoice",
            name="is_deleted",
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name="product",
            name="deleted_at",
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name="product",
            name="is_deleted",
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name="purchase",
            name="deleted_at",
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name="purchase",
            name="is_deleted",
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="print_auto_expand_height",
            field=models.BooleanField(
                default=True,
                help_text="Auto-expand height for longer bills so nothing is cut off",
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="print_custom_height_mm",
            field=models.DecimalField(
                blank=True,
                decimal_places=1,
                help_text="Custom height in mm",
                max_digits=6,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="print_custom_width_mm",
            field=models.DecimalField(
                decimal_places=1,
                default=Decimal("80.0"),
                help_text="Custom width in mm",
                max_digits=6,
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="print_font_scaling",
            field=models.CharField(
                default="auto", help_text="Font scaling mode", max_length=20
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="print_paper_height_mode",
            field=models.CharField(
                choices=[
                    (
                        "auto",
                        "Auto-Fit / Continuous Roll (உள்ளடக்கத்திற்கு ஏற்ப தானாக)",
                    ),
                    ("fixed", "Fixed Height (நிலையான உயரம்)"),
                ],
                default="auto",
                help_text="Height mode: auto or fixed",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="print_paper_size",
            field=models.CharField(
                choices=[
                    ("80mm", "80mm (3 Inch Thermal Standard - Recommended)"),
                    ("58mm", "58mm (2 Inch Thermal Mini)"),
                    ("100mm", "100mm (4 Inch Wide Thermal)"),
                    ("a5", "A5 Sheet (148mm × 210mm)"),
                    ("a4", "A4 Sheet (210mm × 297mm)"),
                    ("custom", "Custom Width & Height (தனிப்பயன் அளவு)"),
                ],
                default="80mm",
                help_text="Bill paper size",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="activitylog",
            name="action_type",
            field=models.CharField(
                choices=[
                    ("LOGIN", "User Login"),
                    ("LOGOUT", "User Logout"),
                    ("INVOICE_CREATE", "Invoice Created"),
                    ("PAYMENT_UPDATE", "Payment Updated"),
                    ("DISCOUNT_APPLIED", "Offer / Discount Applied"),
                    ("PRODUCT_ADD", "Product Added"),
                    ("PRODUCT_EDIT", "Product Edited"),
                    ("PRODUCT_DELETE", "Product Removed"),
                    ("CUSTOMER_ADD", "Customer Added"),
                    ("CUSTOMER_EDIT", "Customer Altered"),
                    ("USER_CREATE", "User Created"),
                    ("USER_EDIT", "User Account Edited"),
                    ("USER_DELETE", "User Account Deleted"),
                    ("SESSION_REVOKE", "Device Session Disconnected"),
                    ("PASSWORD_CHANGE", "Password Reset"),
                    ("INVOICE_EDIT", "Invoice Altered / Edited"),
                    ("DATA_CLEANUP", "Data Cleanup"),
                    ("COMPANY_UPDATE", "Company Profile & Branding Updated"),
                    ("BRANCH_CREATE", "Shop Branch Created"),
                    ("BRANCH_EDIT", "Shop Branch Updated"),
                    ("BRANCH_DELETE", "Shop Branch Deleted"),
                    ("STOCK_ADD", "Stock Inward / Added"),
                    ("STOCK_UPDATE", "Stock Quantity Adjusted"),
                    ("CUSTOMER_DELETE", "Customer Record Deleted"),
                    ("UPDATE_PUBLISH", "Software Update Published"),
                    ("PROFILE_UPDATE", "Client Profile & Business Details Updated"),
                    ("REPORT_EXPORT", "Statement / Sales Report Exported"),
                    ("DEVICE_REGISTER", "Device Registered / Activated"),
                    ("DEVICE_REVOKE", "Device Access Revoked"),
                    ("DEVICE_LIMIT_BLOCKED", "Device Quota Exceeded Blocked"),
                    ("DEVICE_OTP", "New Device Verification OTP"),
                    ("DEVICE_VERIFY", "Device OTP Verified & Approved"),
                    ("RECYCLE_BIN_DELETE", "Item Moved to Recycle Bin"),
                    ("RECYCLE_BIN_RESTORE", "Item Restored from Recycle Bin"),
                    ("RECYCLE_BIN_PURGE", "Item Permanently Deleted"),
                    (
                        "PRINT_CONFIG_UPDATE",
                        "Bill Paper Size & Print Configuration Updated",
                    ),
                ],
                db_index=True,
                max_length=50,
            ),
        ),
        migrations.CreateModel(
            name="SavedReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("report_name", models.CharField(max_length=200)),
                (
                    "report_type",
                    models.CharField(
                        choices=[
                            ("sales", "Sales Report"),
                            ("gst", "GST Tax Report"),
                            ("customer", "Customer Outstanding Statement"),
                            ("inventory", "Inventory & Stock Report"),
                            ("profit_loss", "Profit & Loss Statement"),
                        ],
                        default="sales",
                        max_length=50,
                    ),
                ),
                ("date_range_label", models.CharField(default="", max_length=150)),
                (
                    "total_amount",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=12
                    ),
                ),
                ("records_count", models.IntegerField(default=0)),
                ("parameters_json", models.TextField(blank=True, default="{}")),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                (
                    "deleted_at",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "client",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="saved_reports",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
