# Generated by Django 5.0.6 on 2026-10-09 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("billing", "0014_customer_deleted_at_customer_is_deleted_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="productcategory",
            name="deleted_at",
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name="productcategory",
            name="is_deleted",
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
