# Generated by Django on 2026-10-09
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("billing", "0015_productcategory_deleted_at_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="DeletedClient",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("username", models.CharField(db_index=True, max_length=150, unique=True)),
                ("deleted_at", models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
            ],
            options={
                "ordering": ["-deleted_at"],
            },
        ),
        migrations.AddField(
            model_name="userprofile",
            name="deleted_at",
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="is_deleted",
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
